callsign: 3Z9V
dmr_id: 2601239
links:
  qrz.com: https://www.qrz.com/db/3Z9V
  radioid.net: https://database.radioid.net/database/view?callsign=3Z9V
  brandmeister.network: https://brandmeister.network/index.php?page=profile&call=3Z9V
